/* dm_base.h -- core types and scalar math.
 *
 * Everything in this engine is written from scratch: no third-party code,
 * no asset files, no data tables that were not generated by these functions.
 * Dependencies: libc (math.h, stdint.h) and, for threading/IO, the Win32 API.
 */
#ifndef DM_BASE_H
#define DM_BASE_H

#include <stdint.h>
#include <stddef.h>
#include <math.h>

typedef float    f32;
typedef double   f64;
typedef uint8_t  u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef int8_t   i8;
typedef int16_t  i16;
typedef int32_t  i32;
typedef int64_t  i64;

#define DM_PI       3.14159265358979323846f
#define DM_TAU      6.28318530717958647692f
#define DM_HALFPI   1.57079632679489661923f
#define DM_INVPI    0.31830988618379067154f
#define DM_SQRT2    1.41421356237309504880f
#define DM_GOLDEN   1.61803398874989484820f
#define DM_D2R      (DM_PI / 180.0f)

#define DM_MIN(a, b)  ((a) < (b) ? (a) : (b))
#define DM_MAX(a, b)  ((a) > (b) ? (a) : (b))
#define DM_ABS(a)     ((a) < 0 ? -(a) : (a))
#define DM_COUNT(a)   ((int)(sizeof(a) / sizeof((a)[0])))
#define DM_SWAP(T, a, b) do { T dm__t = (a); (a) = (b); (b) = dm__t; } while (0)

/* ---- clamping and interpolation ------------------------------------- */

static inline f32 dm_clamp(f32 x, f32 a, f32 b) { return x < a ? a : (x > b ? b : x); }
static inline f32 dm_sat(f32 x)                 { return dm_clamp(x, 0.0f, 1.0f); }
static inline f32 dm_lerp(f32 a, f32 b, f32 t)  { return a + (b - a) * t; }
static inline f32 dm_fract(f32 x)               { return x - floorf(x); }
static inline f32 dm_step(f32 edge, f32 x)      { return x < edge ? 0.0f : 1.0f; }
static inline f32 dm_sign(f32 x)                { return x < 0.0f ? -1.0f : (x > 0.0f ? 1.0f : 0.0f); }
static inline f32 dm_mod(f32 x, f32 m)          { return x - m * floorf(x / m); }
static inline f32 dm_sq(f32 x)                  { return x * x; }

static inline f32 dm_smoothstep(f32 a, f32 b, f32 x)
{
    f32 t = dm_sat((x - a) / (b - a));
    return t * t * (3.0f - 2.0f * t);
}

/* C2-continuous variant: no visible derivative kink, matters for slow ramps. */
static inline f32 dm_smootherstep(f32 a, f32 b, f32 x)
{
    f32 t = dm_sat((x - a) / (b - a));
    return t * t * t * (t * (t * 6.0f - 15.0f) + 10.0f);
}

static inline f32 dm_remap(f32 x, f32 a, f32 b, f32 c, f32 d)
{
    return c + (d - c) * dm_sat((x - a) / (b - a));
}

/* Unclamped remap, for coordinate transforms rather than fades. */
static inline f32 dm_remapu(f32 x, f32 a, f32 b, f32 c, f32 d)
{
    return c + (d - c) * ((x - a) / (b - a));
}

/* ---- periodic shapes -------------------------------------------------- */

/* All return 0..1 over a period of 1. */
static inline f32 dm_tri(f32 x)  { f32 t = dm_fract(x); return t < 0.5f ? t * 2.0f : 2.0f - t * 2.0f; }
static inline f32 dm_saw(f32 x)  { return dm_fract(x); }
static inline f32 dm_sqr(f32 x, f32 duty) { return dm_fract(x) < duty ? 1.0f : 0.0f; }
static inline f32 dm_sin01(f32 x) { return 0.5f + 0.5f * sinf(x * DM_TAU); }

/* Band-limited-ish pulse: 1 inside [a,b), 0 outside, with soft edges of width w. */
static inline f32 dm_pulse(f32 a, f32 b, f32 w, f32 x)
{
    return dm_smoothstep(a - w, a + w, x) - dm_smoothstep(b - w, b + w, x);
}

/* ---- easing ----------------------------------------------------------- */

static inline f32 dm_ease_in_quad(f32 t)      { return t * t; }
static inline f32 dm_ease_out_quad(f32 t)     { f32 u = 1.0f - t; return 1.0f - u * u; }
static inline f32 dm_ease_in_cubic(f32 t)     { return t * t * t; }
static inline f32 dm_ease_out_cubic(f32 t)    { f32 u = 1.0f - t; return 1.0f - u * u * u; }
static inline f32 dm_ease_in_out_cubic(f32 t) { return t < 0.5f ? 4.0f * t * t * t : 1.0f - 4.0f * dm_sq(1.0f - t) * (1.0f - t); }
static inline f32 dm_ease_in_quint(f32 t)     { f32 t2 = t * t; return t2 * t2 * t; }
static inline f32 dm_ease_out_expo(f32 t)     { return t >= 1.0f ? 1.0f : 1.0f - powf(2.0f, -10.0f * t); }
static inline f32 dm_ease_in_expo(f32 t)      { return t <= 0.0f ? 0.0f : powf(2.0f, 10.0f * t - 10.0f); }

/* Overshoots past 1 then settles -- gives logo/text entries some weight. */
static inline f32 dm_ease_out_back(f32 t)
{
    const f32 c1 = 1.70158f, c3 = c1 + 1.0f;
    f32 u = t - 1.0f;
    return 1.0f + c3 * u * u * u + c1 * u * u;
}

static inline f32 dm_ease_out_elastic(f32 t)
{
    const f32 c4 = DM_TAU / 3.0f;
    if (t <= 0.0f) return 0.0f;
    if (t >= 1.0f) return 1.0f;
    return powf(2.0f, -10.0f * t) * sinf((t * 10.0f - 0.75f) * c4) + 1.0f;
}

static inline f32 dm_ease_out_bounce(f32 t)
{
    const f32 n1 = 7.5625f, d1 = 2.75f;
    if (t < 1.0f / d1)      return n1 * t * t;
    if (t < 2.0f / d1)      { t -= 1.5f  / d1; return n1 * t * t + 0.75f; }
    if (t < 2.5f / d1)      { t -= 2.25f / d1; return n1 * t * t + 0.9375f; }
    t -= 2.625f / d1;       return n1 * t * t + 0.984375f;
}

/* Exponential decay, the shape of every percussive envelope in the demo. */
static inline f32 dm_decay(f32 t, f32 halflife)
{
    return t < 0.0f ? 0.0f : powf(0.5f, t / halflife);
}

/* ---- misc ------------------------------------------------------------- */

/* Smooth minimum (Inigo Quilez polynomial form). Blends SDFs without a seam. */
static inline f32 dm_smin(f32 a, f32 b, f32 k)
{
    f32 h = dm_sat(0.5f + 0.5f * (b - a) / k);
    return dm_lerp(b, a, h) - k * h * (1.0f - h);
}

static inline f32 dm_smax(f32 a, f32 b, f32 k)
{
    f32 h = dm_sat(0.5f - 0.5f * (b - a) / k);
    return dm_lerp(b, a, h) + k * h * (1.0f - h);
}

#endif /* DM_BASE_H */
